# Generated by Django 5.1.2 on 2024-12-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='None', upload_to=''),
            preserve_default=False,
        ),
    ]
